services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    networks:
      - server-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
    networks:
      - server-network

networks:
  server-network:
    name: server-network
